vm_name: rhel11
#memory_in_kib:
#num_vcpus:
#disk_path:
#iso_name:

users:
  - cnovak
  - mnovak
  - kimstewart
service_accounts:
  - ansible


common_packages:
  - podman
  - bind-utils
  - libguestfs-tools
  - cloud-init
  - virt-install
  - lm_sensors
  - python3-jmespath
  - cockpit
  - cockpit-machines
  - openssh-askpass
  - nfs-utils
  - ansible-core
  - git
