#!/usr/bin/ansible-playbook
- hosts: localhost
  tasks:
  - name: Install collections
    community.general.ansible_galaxy_install:
      type: collection
      requirements_file: "{{ playbook_dir }}/../collections/requirements.yml"
